### ISSUE TITLE
Software request: sci-biology/salmon

### ISSUE THREAD

**Issue by klmr** [EBI-predocs/research-software#65]
Here’s my `$PATH`:

```bash
⟩⟩⟩ IFS=:; for p in $PATH; do echo $p; done
/homes/rudolph/.local/bin
/homes/rudolph/bin
/homes/rudolph/node_modules/.bin
/homes/rudolph/nfs/opt/wiggle/bin
/homes/rudolph/nfs/opt/gcc-4.8.2/bin
/nfs/research2/software/prefix/usr/local/bin
/nfs/research2/software/prefix/usr/bin
/nfs/research2/software/prefix/bin
/nfs/research2/software/prefix/opt/bin
/nfs/research2/software/prefix/usr/sbin
/nfs/research2/software/prefix/sbin
/nfs/research2/software/prefix/usr/x86_64-pc-linux-gnu/gcc-bin/4.8.5
/usr/bin
/bin
/ebi/lsf/ebi/9.1/linux2.6-glibc2.3-x86_64/bin
```

The first five are set by my `.bashrc`. The rest is set by the global configuration of my shell (`/nfs/research2/software/prefix/bin/bash`). However, some of those paths do not exist (`/nfs/research2/software/prefix/usr/local/bin`, `/nfs/research2/software/prefix/opt/bin`).

In addition, some software that was previous installed cannot be found any longer. I don’t have an exhaustive list but one example is `salmon`. Is it possible that these paths used to exist and were deleted?

**Comment by mschubert** [comment]
`usr/local` should not be used by portage (and neither created; but the path *is* set by the shell so manually installed binaries can be found). This is intentional and there is no mistake here.

Software is still missing because of #52.

Unfortunately, there were some complications with the handover to @mattjeffryes so I can't install anything new on yoda right now (and neither can he).

For EBI you're in luck, that still works for me. But the `salmon` ebuild is currently broken, might give it a try tomorrow.

**Comment by mschubert** [comment]
That was easier than expected: https://github.com/EBI-predocs/research-software/commit/15ce9b79d13348ea7228ea0e50bea685f2bf3ce6
